"""Stable identifiers and thresholds for the v1 guardrail catalog."""

GLOBAL_MIN_N = "GLOBAL-MIN-N"
COMP_MIN_ARM = "COMP-MIN-ARM"
EPV_LOGISTIC = "EPV-LOGISTIC"
SURV_CENSOR = "SURV-CENSOR"
SURV_EVENTS = "SURV-EVENTS"
UMAP_MIN_N = "UMAP-MIN-N"
UNCHECKED_FRACTION = "UNCHECKED-FRACTION"
MEAS_UNITS = "MEAS-UNITS"
TRAJECTORY_MIXED_MIN = "TRAJ-MIXED-MIN"
CAUSAL_ADJUSTMENT = "CAUSAL-ADJUSTMENT"
CAUSAL_MIN = "CAUSAL-MIN"
MULTIPLICITY = "MULTIPLICITY"
CODESET_APPROVAL = "CODESET-APPROVAL"

COMPARATIVE_MIN_N = 10
MIN_ARM_N = 5
EPV_REFUSE_BELOW = 5.0
EPV_WARN_BELOW = 10.0
SURVIVAL_MIN_EVENTS_PER_ARM = 5
UMAP_REFUSE_BELOW = 30
UMAP_WARN_BELOW = 100
UNCHECKED_WARN_ABOVE = 0.20
UNCHECKED_REFUSE_ABOVE = 0.50
CAUSAL_MIN_EXPOSED = 20
CAUSAL_MIN_EVENTS = 10
MIXED_MODEL_MIN_PATIENTS = 30
MIXED_MODEL_MIN_MEDIAN_MEASUREMENTS = 3.0
